from src.orderings.dimensionality_reduction import DroPca, DroMDS, DroTSNE
DIMENSIONALITY_REDUCTION_METHOD_PCA = 'PCA'
DIMENSIONALITY_REDUCTION_METHOD_MDS = 'MDS'
DIMENSIONALITY_REDUCTION_METHOD_TSNE = 'TSNE'
RADIAL_LAYOUT_BRANCH_LENGTH = 'BRANCH_LENGTH'
RADIAL_LAYOUT_LEAF_COUNT = 'LEAF_COUNT'

DIMENSIONALITY_REDUCTION_METHOD_MAPPINGS = {
    DIMENSIONALITY_REDUCTION_METHOD_PCA: DroPca,
    DIMENSIONALITY_REDUCTION_METHOD_MDS: DroMDS,
    DIMENSIONALITY_REDUCTION_METHOD_TSNE: DroTSNE,
}